[tox]
envlist = py312
isolated_build = true

[testenv]
deps =
    httpx
    pytest
    pytest-cov
    pytest-girder>=5.0.0a5
commands =
    pytest \
        --cov=girder_async_routes \
        --cov-report=term-missing \
        --cov-report=xml \
        {posargs}
