[tox]
envlist = lint,pytest
skipsdist = true
isolated_build = true

[gh-actions]
python =
    3.12: pytest, lint

[testenv]
package = wheel
wheel_build = .pkg

[testenv:pytest]
deps =
    httpx
    pytest
    pytest-cov
    pytest-girder>=5.0.0a5
commands =
    pytest \
        --cov=girder_async_routes \
        --cov-report=term-missing \
        --cov-report=xml \
        {posargs}

[testenv:lint]
skip_install = true
skipdist = true
deps =
  ruff
commands =
  ruff check --select ALL --show-source --statistics .

[pytest]
junit_family = xunit2
testpaths = tests
